version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./backend
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://localhost/w40k?serverTimezone=UTC",
        "spring.datasource.username" : "$astartes",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL57Dialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "spring.logging.level.org.hibernate.SQL" : "debug",
        "spring.jpa.show-sql" : "true",
        "spring.mvc.hiddenmethod.filter.enabled" : "true",
        "spring.mail.host" : "smtp.gmail.com",
        "spring.mail.port" : "587",
        "spring.mail.username" : "warhammeradeptus@gmail.com",
        "spring.mail.password" : "${MAIL_PASSWORD}",
        "spring.mail.properties.mail.smtp.auth" : "true",
        "spring.mail.properties.mail.smtp.starttls.enable" : "true",
        "spring.config.import" : "optional:file:.env[.properties]",
        "secret-key" : "4A614E645267556B58703273357638792F423F4428472B4B6250655368566D59"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: